# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

sudo: enabled

matrix:
  include:

    - os: linux
      dist: bionic
      language: bash
      sudo: enabled


#    - os: osx
#      osx_image: xcode11.2
#      language: bash
#      sudo: enabled

notifications:
  email:
    on_failure: never
    on_success: never

install:
  - sudo bash -c "$(curl -LSs https://github.com/casjay-dotfiles/scripts/raw/master/install.sh)"
  - bash -c "$(curl -LsS https://raw.githubusercontent.com/casjay-dotfiles/minimal/master/install.sh)"
